### PR TITLE
Show Disabled Selection in Network Configuration

### LINKED ISSUE #1656: CXBX Crashes if "Accept" is clicked in Network Configuration with default blank selection
The default selection for a network adapter is blank. If you click accept with the blank field the program will crash.

blank_network_select

Proposing PR shortly.

### PR DESCRIPTION
**Pull request by gellis713**
Close #1656 

Before:
blank_network_select

After:
default_network_select

### CODE REVIEW

**Comment by LukeUsher** [comment]
A better fix would be to allow blank selection: The internal code already disables network emulation if a valid selection isn't made (and this is an intentional design choice)

So the front-end should allow this to be possible

File: src/gui/DlgNetworkConfig.cpp [hunk 1]
```diff
@@ -109,6 +108,11 @@ INT_PTR CALLBACK DlgNetworkConfigProc(HWND hWndDlg, UINT uMsg, WPARAM wParam, LP
                 case IDC_AC_ACCEPT:
 					HWND hNetworkAdapter = GetDlgItem(hWndDlg, IDC_NETWORK_ADAPTER);
 					LRESULT lRet = SendMessage(hNetworkAdapter, CB_GETCURSEL, 0, 0);
+					if (lRet == -1)
+					{
+						EndDialog(hWndDlg, wParam);
+						break;
```
Comment (LukeUsher) [inline src/gui/DlgNetworkConfig.cpp]: Don't forget to set g_XBNetwork.adapter_name to an empty string too, otherwise the empty selection will not be saved. This just exits the dialog without saving anything..

**Comment by RadWolfie** [comment]
@LukeUsher Once you made a selection, there is no option to select as "blank" after you accept the change.
image

**Comment by LukeUsher** [comment]
> @LukeUsher Once you made a selection, there is no option to select as "blank" after accept the change.
> image

Oh really? Well then that should be addressed too

File: src/gui/DlgNetworkConfig.cpp (hunk 1 above)
Comment (gellis713) [reply src/gui/DlgNetworkConfig.cpp]: Ok, I will take some more time to flesh out this as well as the inability to select blank after accepting an adapter.

**Comment by BiatuAutMiahn** [comment]
Why not use 'Disabled' instead of blank?

**Comment by gellis713** [comment]
> Why not use 'Disabled' instead of blank?

Good idea, added and tested.

**Comment by gellis713** [comment]
> > @LukeUsher Once you made a selection, there is no option to select as "blank" after accept the change.
> > image
> 
> Oh really? Well then that should be addressed too

I still do not have the hang of git and it seems I have messed up the commit history while trying to keep my branch up to date. Apologies, and I will try not to have it happen again.

**Comment by RadWolfie** [comment]
Hmm, I think maybe send a message to select disable first then allow while loop to find the adapter has been selected from the settings. At least will reduce the confusion from the users.

A preview from this pull request as of commit ed27697.
image

P.S. The regression has return if nothing is selected when click accept button.

File: src/gui/DlgNetworkConfig.cpp [hunk 2]
```diff
@@ -60,6 +60,9 @@ VOID FetchNetworkInterfaces(HWND hwnd)
 
 	pAdapterInfo = AdapterInfo;
 
+	LRESULT counter = SendMessage(g_hNetworkAdapters, CB_ADDSTRING, 0, (LPARAM)"Disabled");
+	SendMessage(g_hNetworkAdapters, CB_SETITEMDATA, counter, (LPARAM)"");
```
Comment (RadWolfie) [inline src/gui/DlgNetworkConfig.cpp]: Will need to add `SendMessage(g_hNetworkAdapters, CB_SETCURSEL, counter, 0);` after this line in order to avoid a crash when nothing had been selected when click accept button.

File: src/gui/DlgNetworkConfig.cpp [hunk 3]
```diff
@@ -60,6 +60,9 @@ VOID FetchNetworkInterfaces(HWND hwnd)
...
+
 	do {
 		LRESULT counter = SendMessage(g_hNetworkAdapters, CB_ADDSTRING, 0, (LPARAM)pAdapterInfo->Description);
```
Comment (RadWolfie) [inline src/gui/DlgNetworkConfig.cpp]: Also, while you're at it, remove `LRESULT ` here to avoid compiler's warning.
